rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-head
before_install:
  - gem update --system
  - gem install turn --version 0.8.2
  - gem install turn --version 0.8.3
jdk:
  - openjdk7
gemfile:
  - gemfiles/rails3.2.gemfile
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: jruby-head
